dnsdist-alt package updated

diff --git a/dnsdist-alt/files/dnsdist-alt.init b/dnsdist-alt/files/dnsdist-alt.init
--- a/dnsdist-alt/files/dnsdist-alt.init
+++ b/dnsdist-alt/files/dnsdist-alt.init
@@ -4,11 +4,21 @@ START=99
 USE_PROCD=1
 
 start_service() {
-	procd_open_instance "dnsdist-alt"
-	procd_set_param command dnsdist --supervised --disable-syslog -C /etc/dnsdist.cfg.lua
-	procd_set_param respawn
-	procd_set_param stdout 1
-	procd_set_param stderr 1
-	procd_set_param limits nofile=4096
-	procd_close_instance
+	if [ "$(uci -q get dnsdist-alt.@dnsdist-alt[0].enabled)" != "1" ]; then
+		echo "dnsdist-alt disabled" | logger -t "dnsdist-alt" -p warn
+	else
+		local startup_script="$(uci -q get dnsdist-alt.@dnsdist-alt[0].startup_script)"
+		[ ! -z "$startup_script" ] && startup_script="/usr/share/dnsdist-alt/dnsdist-alt.lua"
+		if [ ! -f "$startup_script" ]; then
+			echo "provided startup script not found: $startup_script" | logger -t "dnsdist-alt" -p err
+			exit 1
+		fi
+		procd_open_instance "dnsdist-alt"
+		procd_set_param command dnsdist-alt --supervised --disable-syslog -C "$startup_script"
+		procd_set_param respawn ${respawn_threshold:-60} ${respawn_timeout:-1} ${respawn_retry:-5}
+		procd_set_param stdout 1
+		procd_set_param stderr 1
+		procd_set_param limits nofile=4096
+		procd_close_instance
+	fi
 }
